# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '11.0'

use_frameworks!

source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

target 'iOSDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  
  use_frameworks!
  pod 'JJKit'
  # Pods for iOSDemo

end
